### ISSUE TITLE
A Question :) Can I use it?

### ISSUE THREAD

**Issue by ruslan-palahin** [NUTSU7/LegionController#1]
Hi, I am much interested in this project. I bought Legion 5 pro and it's super loud on linux :) Nothing works. Is this one ready for usage? Can I do something in order to help? Thanks, cheers!

**Comment by NUTSU7** [comment]
Hey, check if your bios is "GKCN", if it is then I will send a zip with instructions of the latest test build

**Comment by ruslan-palahin** [comment]
Yes, it looks like GKCN53WW

**Comment by Butyllithium** [comment]
> Hey, check if your bios is "GKCN", if it is then I will send a zip with instructions of the latest test build

Hi, my BIOS meets the requirements, can I take the test? Please. 
(English is not my native language; please excuse typing errors.)
