### ISSUE TITLE
Development Status

### ISSUE THREAD

**Issue by saul-jb** [NUTSU7/LegionController#3]
Whats the status of this project, are you still planning on finishing it? I am asking because if you have dropped it, I will fork it or try create something similar when I have the time.

**Comment by NUTSU7** [comment]
Hey, the project should be basic but I'm not planning on finishing it for now, you can fork it and evolve it as u like

**Comment by saul-jb** [comment]
What state is it currently in? What works/doesn't? Does the installation script work and setup everything needed?

Thanks.

**Comment by NUTSU7** [comment]
Technically everything that is there should work

**Comment by saul-jb** [comment]
Cool, it does seem that most things work but are not incredibly stable, I have a couple more questions after messing with it for some time:

- Where did you find the info on what registers to write to in order to alter things like power mode and fan speed? (Getting a little bit of odd behavior loading and unloading the kernel module.)
- Do you have any idea why manually writing to cFanCurve (`echo -n "30" > cFanCurve`) does not work but the python program (that does the same thing) does work? As far as I can see in the kernel module it shouldn't matter.

**Comment by NUTSU7** [comment]
- the info about the registers was taken from undervolt the one who found fan control and with the module smokeless helped me
- echo needs to be with sudo iirc
